plugins:
  - jekyll-remote-theme

remote_theme: jekyll/minima

title: blog.mouais.net
description: Blog d'un passionné des réseaux !
url: "https://blog.mouais.net"

minima:
  show_excerpts: true
  social_links:
    - title: Alexis La Goutte repository at GitHub
      icon: github
      url: "https://github.com/alagoutte"
    - title: Alexis La Goutte at X (twitter)
      icon: x-twitter
      url: "https://x.com//alagoutte"
    - title: Alexis La Goutte at Linkedin
      icon: linkedin
      url: "https://www.linkedin.com/in/alexis-lagoutte"
