plugins:
  - jekyll-remote-theme

remote_theme: jekyll/minima

title: blog.mouais.net
description: Blog d'un passionné des réseaux !
url: "https://blog.mouais.net"

minima:
  social_links:
    - { platform: github, user_url: "https://github.com/alagoutte" }
    - {
        platform: linkedin,
        user_url: "https://www.linkedin.com/in/alexis-lagoutte",
      }
    - { platform: x, user_url: "https://x.com/alagoutte" }
